Repository Nexters/Boolti-iOS, pull requests merged in 2024-09, with the labels that each got.

#336 Release Version 1.6.2
  Boolti/Boolti.xcodeproj/project.pbxproj
  Boolti/Boolti/Resources/Assets.xcassets/banner_background.imageset/Contents.json
  Boolti/Boolti/Resources/Assets.xcassets/banner_background.imageset/banner_background.png
  Boolti/Boolti/Resources/Assets.xcassets/banner_fire.imageset/Contents.json
  Boolti/Boolti/Resources/Assets.xcassets/banner_fire.imageset/banner_fire.png
  Boolti/Boolti/Sources/Global/Extensions/Preview.swift
  Boolti/Boolti/Sources/UILayer/Concert/ConcertList/Cells/BannerCollectionViewCell.swift
  Boolti/Boolti/Sources/UILayer/Concert/ConcertList/ConcertListViewController.swift
  Boolti/Boolti/Sources/UILayer/Concert/ConcertList/ConcertViewModel.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/Detail/GiftingDetail/GiftingDetailViewController.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/Detail/TicketingDetail/TicketingDetailViewController.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/Detail/ViewController/AgreementViewController.swift
Labels: ETC

#337 Feature/#325 프로필 디테일뷰 구현
  Boolti/Boolti.xcodeproj/project.pbxproj
  Boolti/Boolti/Application/AppDelegate.swift
  Boolti/Boolti/Resources/Assets.xcassets/link.imageset/Contents.json
  Boolti/Boolti/Resources/Assets.xcassets/link.imageset/link.pdf
  Boolti/Boolti/Resources/Assets.xcassets/pencil.imageset/Contents.json
  Boolti/Boolti/Resources/Assets.xcassets/pencil.imageset/pencil.pdf
  Boolti/Boolti/Sources/Network/DTO/Auth/Response/UserResponseDTO.swift
  Boolti/Boolti/Sources/Network/Repositories/Auth/AuthRepository.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Main/MyPageDIContainer.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Main/MyPageDestination.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Main/MyPageViewModel.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Main/MypageViewController.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Main/Views/MypageProfileView.swift
  Boolti/Boolti/Sources/UILayer/MyPage/MyPageDIContainer.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/Cells/ProfileLinkCollectionViewCell.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/ProfileDIContainer.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/ProfileViewController.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/ProfileViewModel.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/Views/ProfileLinkHeaderView.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/Views/ProfileMainView.swift
Labels: 1.6.3

#340 Feature/#327 EditLink 구현하기
  Boolti/Boolti.xcodeproj/project.pbxproj
  Boolti/Boolti/Resources/Assets.xcassets/delete.imageset/Contents.json
  Boolti/Boolti/Resources/Assets.xcassets/delete.imageset/icon.png
  Boolti/Boolti/Resources/Assets.xcassets/delete.imageset/icon@2x.png
  Boolti/Boolti/Resources/Assets.xcassets/delete.imageset/icon@3x.png
  Boolti/Boolti/Sources/UILayer/Common/BooltiNavigationBar.swift
  Boolti/Boolti/Sources/UILayer/Common/BooltiPopupView.swift
  Boolti/Boolti/Sources/UILayer/Common/BooltiTextField.swift
  Boolti/Boolti/Sources/UILayer/MyPage/EditLink/BooltiInputStackView.swift
  Boolti/Boolti/Sources/UILayer/MyPage/EditLink/ButtonTextField.swift
  Boolti/Boolti/Sources/UILayer/MyPage/EditLink/EditLinkViewController.swift
Labels: v1.6.1

#341 Fix/#339 profile height
  Boolti/Boolti.xcodeproj/project.pbxproj
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/EditProfile/Views/EditIntroductionView.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/Main/ProfileViewController.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/Main/ProfileViewModel.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/Main/Views/ProfileMainView.swift
Labels: 1.6.3

#344 Fix/#343 Edit Link 폴더 인식 이슈 해결 & 네비게이션 중괄호 이슈 해결
  Boolti/Boolti.xcodeproj/project.pbxproj
  Boolti/Boolti/Sources/UILayer/Common/BooltiNavigationBar.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/EditProfile/EditProfileViewController.swift
Labels: 1.6.3

#345 Feature/#342 프로필 이미지 업로드 구현
  Boolti/Boolti.xcodeproj/project.pbxproj
  Boolti/Boolti/Sources/Network/APIs/AuthAPI.swift
  Boolti/Boolti/Sources/Network/DTO/Auth/Request/UploadProfileImageRequestDTO.swift
  Boolti/Boolti/Sources/Network/DTO/Auth/Response/GetUploadURLReponseDTO.swift
  Boolti/Boolti/Sources/Network/Foundation/AuthInterceptor.swift
  Boolti/Boolti/Sources/Network/Foundation/NetworkProvider.swift
  Boolti/Boolti/Sources/Network/Repositories/Auth/AuthRepository.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/EditProfile/EditProfileViewController.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/EditProfile/EditProfileViewModel.swift
Labels: 1.6.3

#349 Fix/#348 MVP 7 QA 반영
  Boolti/Boolti.xcodeproj/project.pbxproj
  Boolti/Boolti/Sources/Network/APIs/AuthAPI.swift
  Boolti/Boolti/Sources/Network/Repositories/Auth/AuthRepository.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Main/Views/MypageProfileView.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/EditLink/EditLinkDIContainer.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/EditLink/EditLinkViewController.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/EditLink/EditLinkViewModel.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/EditProfile/Cells/EditLinkCollectionViewCell.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/EditProfile/EditProfileDIContainer.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/EditProfile/EditProfileViewController.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/EditProfile/EditProfileViewModel.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/EditProfile/Views/EditIntroductionView.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/EditProfile/Views/EditNicknameView.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/EditProfile/Views/EditProfileImageView.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/Main/ProfileViewController.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/Main/Views/ProfileMainView.swift
Labels: 1.6.3

#351 Fix/#350 MVP7 QA(2) 수정사항 반영 완료
  Boolti/Boolti/Sources/Network/DTO/Auth/Response/UserResponseDTO.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/EditProfile/EditProfileViewController.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/EditProfile/EditProfileViewModel.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/EditProfile/Views/EditNicknameView.swift
Labels: 1.6.3

#353 Feature/#352 mvp7 qa3
  Boolti/Boolti/Sources/UILayer/Concert/ConcertDetail/ConcertDetailViewController.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/EditLink/EditLinkViewController.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/EditProfile/Views/EditIntroductionView.swift
Labels: 1.6.3

#354 Release Version 1.6.3
  Boolti/Boolti.xcodeproj/project.pbxproj
  Boolti/Boolti/Application/AppDelegate.swift
  Boolti/Boolti/Resources/Assets.xcassets/add_circle.imageset/Contents.json
  Boolti/Boolti/Resources/Assets.xcassets/add_circle.imageset/add_circle.pdf
  Boolti/Boolti/Resources/Assets.xcassets/camera.imageset/Contents.json
  Boolti/Boolti/Resources/Assets.xcassets/camera.imageset/camera.pdf
  Boolti/Boolti/Resources/Assets.xcassets/delete.imageset/Contents.json
  Boolti/Boolti/Resources/Assets.xcassets/delete.imageset/icon.png
  Boolti/Boolti/Resources/Assets.xcassets/delete.imageset/icon@2x.png
  Boolti/Boolti/Resources/Assets.xcassets/delete.imageset/icon@3x.png
  Boolti/Boolti/Resources/Assets.xcassets/link.imageset/Contents.json
  Boolti/Boolti/Resources/Assets.xcassets/link.imageset/link.pdf
  Boolti/Boolti/Resources/Assets.xcassets/pencil.imageset/Contents.json
  Boolti/Boolti/Resources/Assets.xcassets/pencil.imageset/pencil.pdf
  Boolti/Boolti/Sources/Entities/Auth/ProfileEntity.swift
  Boolti/Boolti/Sources/Network/APIs/AuthAPI.swift
  Boolti/Boolti/Sources/Network/DTO/Auth/Request/EditProfileRequestDTO.swift
  Boolti/Boolti/Sources/Network/DTO/Auth/Request/UploadProfileImageRequestDTO.swift
  Boolti/Boolti/Sources/Network/DTO/Auth/Response/GetUploadURLReponseDTO.swift
  Boolti/Boolti/Sources/Network/DTO/Auth/Response/UserResponseDTO.swift
  Boolti/Boolti/Sources/Network/Foundation/AuthInterceptor.swift
  Boolti/Boolti/Sources/Network/Foundation/NetworkProvider.swift
  Boolti/Boolti/Sources/Network/Repositories/Auth/AuthRepository.swift
  Boolti/Boolti/Sources/UILayer/Common/BooltiInputStackView.swift
  Boolti/Boolti/Sources/UILayer/Common/BooltiNavigationBar.swift
  Boolti/Boolti/Sources/UILayer/Common/BooltiPopupView.swift
  Boolti/Boolti/Sources/UILayer/Common/BooltiTextField.swift
  Boolti/Boolti/Sources/UILayer/Common/ButtonTextField.swift
  Boolti/Boolti/Sources/UILayer/Concert/ConcertDetail/ConcertDetailViewController.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Main/MyPageDIContainer.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Main/MyPageDestination.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Main/MyPageViewModel.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Main/MypageViewController.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Main/Views/MypageProfileView.swift
  Boolti/Boolti/Sources/UILayer/MyPage/MyPageDIContainer.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/EditLink/EditLinkViewController.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/EditLink/EditLinkViewModel.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/EditProfile/Cells/EditLinkCollectionViewCell.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/EditProfile/EditProfileDIContainer.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/EditProfile/EditProfileViewController.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/EditProfile/EditProfileViewModel.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/EditProfile/Views/AddLinkHeaderView.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/EditProfile/Views/EditIntroductionView.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/EditProfile/Views/EditLinkView.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/EditProfile/Views/EditNicknameView.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/EditProfile/Views/EditProfileImageView.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/Main/Cells/ProfileLinkCollectionViewCell.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/Main/ProfileDIContainer.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/Main/ProfileViewController.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/Main/ProfileViewModel.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/Main/Views/ProfileLinkHeaderView.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/Main/Views/ProfileMainView.swift
Labels: ETC
