Repository Nexters/Boolti-iOS, pull requests merged in 2024-04, with the labels that each got.

#179 Chore/#175 티켓 N매 구매, 0원 결제, 초청코드 분기처리
  Boolti/Boolti.xcodeproj/project.pbxproj
  Boolti/Boolti/Resources/Assets.xcassets/minus.imageset/Contents.json
  Boolti/Boolti/Resources/Assets.xcassets/minus.imageset/minus.pdf
  Boolti/Boolti/Resources/Assets.xcassets/plus.imageset/Contents.json
  Boolti/Boolti/Resources/Assets.xcassets/plus.imageset/plus.pdf
  Boolti/Boolti/Sources/Entities/Concert/SelectedTicketEntity.swift
  Boolti/Boolti/Sources/Entities/Concert/salesTicketingEntity.swift
  Boolti/Boolti/Sources/Global/Extensions/UILabel+.swift
  Boolti/Boolti/Sources/Network/DTO/Concert/Response/SalesTicketResponseDTO.swift
  Boolti/Boolti/Sources/Network/Repositories/ConcertRepository.swift
  Boolti/Boolti/Sources/UILayer/Common/BooltiBottomSheetViewController.swift
  Boolti/Boolti/Sources/UILayer/Common/BooltiPopupView.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TicketSelection/Cells/SelectedTicketTableViewCell.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TicketSelection/Cells/TicketTypeTableViewCell.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TicketSelection/TicketSelectionViewController.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TicketSelection/TicketSelectionViewModel.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TicketSelection/Views/SelectedInvitationTicketView.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TicketSelection/Views/SelectedSalesTicketView.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TicketSelection/Views/SelectedTicketView.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TicketSelection/Views/TicketTypeView.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TicketingCompletion/TicketingCompletionViewController.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TicketingCompletion/Views/ReservedTicketView.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TicketingConfirm/TicketingConfirmViewController.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TicketingConfirm/TicketingConfirmViewModel.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TicketingDetail/TicketingDetailViewController.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TicketingDetail/TicketingDetailViewModel.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TicketingDetail/Views/MiddlemanPolicyView.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TicketingDetail/Views/TicketInfoView.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TicketingDetail/Views/UserInfoInputView.swift
  Boolti/Boolti/Sources/UILayer/MyPage/QRScanner/QRScannerList/QRScannerListViewController.swift
  Boolti/Boolti/Sources/UILayer/Ticket/TicketEntryCode/Views/EntryCodeInputView.swift
  Boolti/Boolti/Sources/UILayer/Update/UpdatePopupViewController.swift
Labels: v1.4.0

#177 Feature/#173 딥링크 구현하기(공연 공유) / 푸시 노티피케이션 수정 / 티켓 UI 수정
  Boolti/Boolti.xcodeproj/project.pbxproj
  Boolti/Boolti/Application/AppDelegate.swift
  Boolti/Boolti/Application/Info.plist
  Boolti/Boolti/Application/SceneDelegate.swift
  Boolti/Boolti/Boolti.entitlements
  Boolti/Boolti/Sources/Global/Constants/AppInfo.swift
  Boolti/Boolti/Sources/Global/Constants/UserDefaultsKey.swift
  Boolti/Boolti/Sources/Global/Enums/NotificationMessageTitle.swift
  Boolti/Boolti/Sources/Global/Extensions/Notification.Name+.swift
  Boolti/Boolti/Sources/Global/Extensions/UICollectionReusableView+.swift
  Boolti/Boolti/Sources/Global/Extensions/UserDefaults+.swift
  Boolti/Boolti/Sources/UILayer/Concert/ConcertDetail/ConcertDetailViewController.swift
  Boolti/Boolti/Sources/UILayer/Concert/ConcertList/ConcertListViewController.swift
  Boolti/Boolti/Sources/UILayer/TabBar/HomeTabBarController.swift
  Boolti/Boolti/Sources/UILayer/TabBar/HomeTabBarViewModel.swift
  Boolti/Boolti/Sources/UILayer/Ticket/TicketDetail/Views/TicketDetailView.swift
  Boolti/Boolti/Sources/UILayer/Ticket/TicketList/Cells/TicketListCollectionViewCell.swift
  Boolti/Boolti/Sources/UILayer/Ticket/TicketList/TicketListViewController.swift
Labels: v1.4.0

#178 Refactor/#176 환불 UI 변경
  Boolti/Boolti.xcodeproj/project.pbxproj
  Boolti/Boolti/Sources/Entities/Ticket/TicketReservationDetailEntity.swift
  Boolti/Boolti/Sources/Entities/Ticket/TicketReservationItemEntity.swift
  Boolti/Boolti/Sources/Network/DTO/Reservation/Response/TicketReservationDetailResponseDTO.swift
  Boolti/Boolti/Sources/UILayer/MyPage/TicketRefund/TicketRefundConfirm/TicketRefundConfirmDIContainer.swift
  Boolti/Boolti/Sources/UILayer/MyPage/TicketRefund/TicketRefundConfirm/TicketRefundConfirmViewController.swift
  Boolti/Boolti/Sources/UILayer/MyPage/TicketRefund/TicketRefundConfirm/Views/RefundConfirmContentView.swift
  Boolti/Boolti/Sources/UILayer/MyPage/TicketRefund/TicketRefundReason/TicketRefundReasonViewController.swift
  Boolti/Boolti/Sources/UILayer/MyPage/TicketRefund/TicketRefundRequest/TicketRefundRequestViewController.swift
  Boolti/Boolti/Sources/UILayer/MyPage/TicketRefund/TicketRefundRequest/TicketRefundRequestViewModel.swift
  Boolti/Boolti/Sources/UILayer/MyPage/TicketRefund/TicketRefundRequest/Views/AccountContentView.swift
  Boolti/Boolti/Sources/UILayer/MyPage/TicketRefund/TicketRefundRequest/Views/ReversalPolicyConfirmButton.swift
  Boolti/Boolti/Sources/UILayer/MyPage/TicketReservationDetail/TicketReservationDetailViewController.swift
  Boolti/Boolti/Sources/UILayer/MyPage/TicketReservationDetail/Views/ConcertInformationView.swift
  Boolti/Boolti/Sources/UILayer/MyPage/TicketReservationDetail/Views/ReservationCollapsableStackView.swift
  Boolti/Boolti/Sources/UILayer/MyPage/TicketReservationDetail/Views/ReservationHorizontalStackView.swift
  Boolti/Boolti/Sources/UILayer/MyPage/TicketReservationDetail/Views/ViewCollapseImageView.swift
  Boolti/Boolti/Sources/UILayer/Ticket/TicketDetail/Views/ReversalPolicyView.swift
  Boolti/Boolti/Sources/UILayer/Ticket/TicketList/Cells/TicketListCollectionViewCell.swift
Labels: v1.4.0

#181 Fix/#180 concertlist SE UI 깨짐 해결
  Boolti/Boolti.xcodeproj/project.pbxproj
  Boolti/Boolti/Sources/UILayer/Concert/ConcertList/ConcertListViewController.swift
Labels: v1.4.0

#183 Chore/#182 이미 예매한 공연 케이스 삭제
  Boolti/Boolti/Sources/UILayer/Concert/ConcertDetail/ConcertDetailViewModel.swift
Labels: v1.4.0

#185 Fix/#184 취소/환불 규정 뷰 padding label 짤림 이슈 해결
  Boolti/Boolti/Sources/UILayer/Common/BooltiPaddingLabel.swift
  Boolti/Boolti/Sources/UILayer/MyPage/TicketRefund/TicketRefundRequest/TicketRefundRequestViewController.swift
  Boolti/Boolti/Sources/UILayer/MyPage/TicketReservationDetail/TicketReservationDetailViewController.swift
  Boolti/Boolti/Sources/UILayer/Ticket/TicketDetail/Views/ReversalPolicyView.swift
Labels: v1.4.0

#193 Chore/#191 0원 티켓 시 취소 요청 버튼 isHidden 처리
  Boolti/Boolti/Sources/UILayer/MyPage/TicketReservationDetail/TicketReservationDetailViewController.swift
Labels: v1.4.0

#194 Chore/#190 토스트 문구 및 티켓 상태 문구 값 변경
  Boolti/Boolti/Sources/Entities/Ticket/TicketReservationItemEntity.swift
  Boolti/Boolti/Sources/UILayer/MyPage/TicketReservationDetail/TicketReservationDetailViewController.swift
Labels: v1.4.0

#195 Fix/#187 티켓 선택하기 setData 오류 수정 & 애니메이션 제거
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TicketSelection/TicketSelectionViewController.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TicketSelection/TicketSelectionViewModel.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TicketSelection/Views/SelectedSalesTicketView.swift
Labels: v1.4.0

#196 Chore/#186 일반 티켓 - 결제 완료 화면 계좌번호만 복사되도록 변경
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TicketingCompletion/TicketingCompletionViewModel.swift
Labels: v1.4.0

#197 Chore/#189 초청티켓 인풋메시지 변경 & 결제 정보 확인 팝업 텍스트 변경
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TicketingConfirm/TicketingConfirmViewController.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TicketingDetail/Views/InvitationCodeView.swift
Labels: v1.4.0

#201 Chore/#200 불티 로고 아이콘 에셋 변경
  Boolti/Boolti/Resources/Assets.xcassets/boolti_logo.imageset/Contents.json
  Boolti/Boolti/Resources/Assets.xcassets/boolti_logo.imageset/boolti_logo.pdf
  Boolti/Boolti/Resources/Assets.xcassets/boolti_logo.imageset/logo.png
  Boolti/Boolti/Resources/Assets.xcassets/boolti_logo.imageset/logo@2x.png
  Boolti/Boolti/Resources/Assets.xcassets/boolti_logo.imageset/logo@3x.png
  Boolti/Boolti/Sources/UILayer/Ticket/TicketDetail/Views/TicketDetailView.swift
  Boolti/Boolti/Sources/UILayer/Ticket/TicketList/Cells/TicketListCollectionViewCell.swift
Labels: v1.4.0

#199 Chore/#198 환불 정보 뷰 spacing 변경
  Boolti/Boolti/Sources/UILayer/MyPage/TicketRefund/TicketRefundConfirm/TicketRefundConfirmViewController.swift
  Boolti/Boolti/Sources/UILayer/MyPage/TicketRefund/TicketRefundRequest/TicketRefundRequestViewController.swift
  Boolti/Boolti/Sources/UILayer/MyPage/TicketRefund/TicketRefundRequest/Views/AccountContentView.swift
  Boolti/Boolti/Sources/UILayer/MyPage/TicketRefund/TicketRefundRequest/Views/RefundAccountNumberView.swift
Labels: v1.4.0

#202 Chore/#192 딥링크 네비게이션 랜딩 로직 수정 & '환불 내역' 수정
  Boolti/Boolti.xcodeproj/project.pbxproj
  Boolti/Boolti/Application/AppDelegate.swift
  Boolti/Boolti/Application/SceneDelegate.swift
  Boolti/Boolti/Sources/Global/Constants/AppInfo.swift
  Boolti/Boolti/Sources/Global/Constants/UserDefaultsKey.swift
  Boolti/Boolti/Sources/Global/Enums/LandingDestination.swift
  Boolti/Boolti/Sources/Global/Enums/NotificationMessage.swift
  Boolti/Boolti/Sources/Global/Extensions/Notification.Name+.swift
  Boolti/Boolti/Sources/Global/Extensions/UserDefaults+.swift
  Boolti/Boolti/Sources/UILayer/Concert/ConcertDetail/ConcertDetailViewController.swift
  Boolti/Boolti/Sources/UILayer/Concert/ConcertList/ConcertListViewController.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Main/MypageViewController.swift
  Boolti/Boolti/Sources/UILayer/MyPage/TicketRefund/TicketRefundConfirm/TicketRefundConfirmViewController.swift
  Boolti/Boolti/Sources/UILayer/MyPage/TicketReservationDetail/TicketReservationDetailViewController.swift
  Boolti/Boolti/Sources/UILayer/MyPage/TicketReservationDetail/Views/ReservationCollapsableStackView.swift
  Boolti/Boolti/Sources/UILayer/TabBar/HomeTabBarController.swift
  Boolti/Boolti/Sources/UILayer/TabBar/HomeTabBarViewModel.swift
Labels: v1.4.0

#206 Chore/#205 초청티켓 사용 '사용되어요' -> '사용되었어요' 변경
  Boolti/Boolti.xcodeproj/project.pbxproj
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TicketingDetail/Views/InvitationCodeView.swift
Labels: v1.4.0

#208 Chore/#207 close 버튼 위치 변경
  Boolti/Boolti/Sources/UILayer/Concert/PosterExpand/PosterExpandViewController.swift
  Boolti/Boolti/Sources/UILayer/Login/Main/LoginViewController.swift
Labels: v1.4.0

#210 Fix/#209 환불 요청 금액 실제 값으로 변경
  Boolti/Boolti/Sources/UILayer/MyPage/TicketRefund/TicketRefundRequest/TicketRefundRequestViewController.swift
Labels: v1.4.0

#212 Chore/#211 딥링크에서 AppID 제거
  Boolti/Boolti/Sources/UILayer/Concert/ConcertDetail/ConcertDetailViewController.swift
Labels: v1.4.0

#215 Chore/#214 네비바 내 아이콘 위치 변경
  Boolti/Boolti/Sources/UILayer/Common/BooltiNavigationBar.swift
Labels: v1.4.0

#216 Chore/#213 예매 내역, 예매 내역 상세 페이지 ‘입금 확인 중 / 취소 진행 중’ 색상 수정
  Boolti/Boolti.xcodeproj/project.pbxproj
  Boolti/Boolti/Sources/Entities/Ticket/TicketReservationItemEntity.swift
Labels: v1.4.0

#220 Release Version 1.4.1
  Boolti/Boolti/Sources/UILayer/Concert/ConcertDetail/ConcertDetailViewController.swift
Labels: ETC

#224 Feat/#223 환불 정책 Remote Config 연동
  Boolti/Boolti/Sources/Global/Constants/AppInfo.swift
  Boolti/Boolti/Sources/UILayer/Splash/SplashViewController.swift
  Boolti/Boolti/Sources/UILayer/Splash/SplashViewModel.swift
  Boolti/Boolti/Sources/UILayer/Ticket/TicketDetail/Views/ReversalPolicyView.swift
Labels: v1.5.0

#225 Feature/#222 토스 페이먼츠 연동
  Boolti/Boolti.xcodeproj/project.pbxproj
  Boolti/Boolti.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Boolti/Boolti/Application/Info.plist
  Boolti/Boolti/Resources/Assets.xcassets/mini_check_off.imageset/Contents.json
  Boolti/Boolti/Resources/Assets.xcassets/mini_check_off.imageset/mini_check_off.pdf
  Boolti/Boolti/Resources/Assets.xcassets/mini_check_on.imageset/Contents.json
  Boolti/Boolti/Resources/Assets.xcassets/mini_check_on.imageset/mini_check_on.pdf
  Boolti/Boolti/Resources/Colors.xcassets/Toss.colorset/Contents.json
  Boolti/Boolti/Sources/Entities/Concert/salesTicketingEntity.swift
  Boolti/Boolti/Sources/Entities/Ticket/TicketReservationDetailEntity.swift
  Boolti/Boolti/Sources/Network/APIs/ConcertAPI.swift
  Boolti/Boolti/Sources/Network/APIs/TicketingAPI.swift
  Boolti/Boolti/Sources/Network/DTO/Reservation/Response/TicketReservationDetailResponseDTO.swift
  Boolti/Boolti/Sources/Network/DTO/Ticket/Response/TicketDetailResponseDTO.swift
  Boolti/Boolti/Sources/Network/DTO/Ticketing/Request/CheckInvitationCodeRequestDTO.swift
  Boolti/Boolti/Sources/Network/DTO/Ticketing/Request/InvitationTicketingRequestDTO.swift
  Boolti/Boolti/Sources/Network/DTO/Ticketing/Request/OrderPaymentRequestDTO.swift
  Boolti/Boolti/Sources/Network/DTO/Ticketing/Request/SalesTicketRequestDTO.swift
  Boolti/Boolti/Sources/Network/DTO/Ticketing/Request/SalesTicketingRequestDTO.swift
  Boolti/Boolti/Sources/Network/DTO/Ticketing/Request/SavePaymentInfoRequestDTO.swift
  Boolti/Boolti/Sources/Network/DTO/Ticketing/Response/CheckInvitationCodeResponseDTO.swift
  Boolti/Boolti/Sources/Network/DTO/Ticketing/Response/OrderPaymentResponseDTO.swift
  Boolti/Boolti/Sources/Network/DTO/Ticketing/Response/SalesTicketResponseDTO.swift
  Boolti/Boolti/Sources/Network/DTO/Ticketing/Response/SavePaymentInfoResponseDTO.swift
  Boolti/Boolti/Sources/Network/DTO/Ticketing/Response/TicketingResponseDTO.swift
  Boolti/Boolti/Sources/Network/Repositories/ConcertRepository.swift
  Boolti/Boolti/Sources/Network/Repositories/TicketingRepository.swift
  Boolti/Boolti/Sources/UILayer/BusinessInfo/BusinessInfoViewController.swift
  Boolti/Boolti/Sources/UILayer/Common/BooltiNavigationBar.swift
  Boolti/Boolti/Sources/UILayer/Common/BooltiViewController.swift
  Boolti/Boolti/Sources/UILayer/Concert/ConcertDetail/ConcertDetailViewController.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TicketSelection/TicketSelectionViewController.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TicketingCompletion/TicketingCompletionViewController.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TicketingCompletion/TicketingCompletionViewModel.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TicketingCompletion/Views/DepositDetailView.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TicketingCompletion/Views/DepositSummaryView.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TicketingCompletion/Views/PaymentCompletionView.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TicketingCompletion/Views/ReservedTicketView.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TicketingConfirm/TicketingConfirmDIContainer.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TicketingConfirm/TicketingConfirmViewController.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TicketingConfirm/TicketingConfirmViewModel.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TicketingDetail/TicketingDetailDIContainer.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TicketingDetail/TicketingDetailViewController.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TicketingDetail/TicketingDetailViewModel.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TicketingDetail/Views/AgreeView.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TicketingDetail/Views/PaymentMethodView.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TicketingDetail/Views/PolicyView.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TossPayments/TossPaymentViewController.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TossPayments/TossPaymentsDIContainer.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TossPayments/TossPaymentsViewModel.swift
  Boolti/Boolti/Support/Enviroment.swift
Labels: v1.5.0

#229 Feature/#228 0원 티켓 결제 승인 처리
  Boolti/Boolti.xcodeproj/project.pbxproj
  Boolti/Boolti/Sources/Entities/Ticket/TicketReservationDetailEntity.swift
  Boolti/Boolti/Sources/Network/APIs/TicketingAPI.swift
  Boolti/Boolti/Sources/Network/DTO/Reservation/Response/TicketReservationDetailResponseDTO.swift
  Boolti/Boolti/Sources/Network/DTO/Ticketing/Request/FreeTicketingRequestDTO.swift
  Boolti/Boolti/Sources/Network/DTO/Ticketing/Request/OrderPaymentRequestDTO.swift
  Boolti/Boolti/Sources/Network/Repositories/TicketingRepository.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TicketingCompletion/TicketingCompletionDIContainer.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TicketingCompletion/TicketingCompletionViewController.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TicketingCompletion/TicketingCompletionViewModel.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TicketingCompletion/Views/ReservedTicketView.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TicketingConfirm/TicketingConfirmViewController.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TicketingConfirm/TicketingConfirmViewModel.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TicketingDetail/TicketingDetailDIContainer.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TicketingDetail/TicketingDetailViewController.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TicketingDetail/TicketingDetailViewModel.swift
Labels: v1.5.0

#230 Feature/#221 환불 Flow 리팩토링 및 예약 상세 페이지 수정
  Boolti/Boolti.xcodeproj/project.pbxproj
  Boolti/Boolti/Sources/Entities/Ticket/TicketReservationDetailEntity.swift
  Boolti/Boolti/Sources/Entities/Ticket/TicketReservationItemEntity.swift
  Boolti/Boolti/Sources/Network/APIs/TicketReservationAPI.swift
  Boolti/Boolti/Sources/Network/DTO/Reservation/Request/TicketRefundRequestDTO.swift
  Boolti/Boolti/Sources/Network/DTO/Reservation/Response/TicketReservationDetailResponseDTO.swift
  Boolti/Boolti/Sources/Network/DTO/Reservation/Response/TicketReservationItemResponseDTO.swift
  Boolti/Boolti/Sources/Network/Repositories/TicketReservationsRepository.swift
  Boolti/Boolti/Sources/UILayer/Common/BooltiViewController.swift
  Boolti/Boolti/Sources/UILayer/Concert/ConcertList/ConcertViewModel.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TicketingCompletion/TicketingCompletionViewController.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TicketingDetail/TicketingDetailViewController.swift
  Boolti/Boolti/Sources/UILayer/MyPage/TicketRefund/TicketRefundBankSelection/BankEntity.swift
  Boolti/Boolti/Sources/UILayer/MyPage/TicketRefund/TicketRefundBankSelection/Cells/TicketRefundBankCollectionViewCell.swift
  Boolti/Boolti/Sources/UILayer/MyPage/TicketRefund/TicketRefundBankSelection/TicketRefundBankSelectionViewController.swift
  Boolti/Boolti/Sources/UILayer/MyPage/TicketRefund/TicketRefundConfirm/TicketRefundConfirmDIContainer.swift
  Boolti/Boolti/Sources/UILayer/MyPage/TicketRefund/TicketRefundConfirm/TicketRefundConfirmViewController.swift
  Boolti/Boolti/Sources/UILayer/MyPage/TicketRefund/TicketRefundConfirm/TicketRefundConfirmViewModel.swift
  Boolti/Boolti/Sources/UILayer/MyPage/TicketRefund/TicketRefundRequest/TicketRefundRequestViewController.swift
  Boolti/Boolti/Sources/UILayer/MyPage/TicketRefund/TicketRefundRequest/TicketRefundRequestViewModel.swift
  Boolti/Boolti/Sources/UILayer/MyPage/TicketReservationDetail/TicketReservationDetailViewController.swift
  Boolti/Boolti/Sources/UILayer/MyPage/TicketReservationDetail/Views/ReservationHorizontalStackView.swift
Labels: v1.5.0

#232 Feature/#227 결제 완료뷰 버튼으로 탭 이동 & 취소/환불 remote config연결 & 결제 상세 url 연결
  Boolti/Boolti/Sources/Global/Constants/AppInfo.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TicketingCompletion/TicketingCompletionViewController.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TicketingDetail/TicketingDetailViewController.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TicketingDetail/Views/AgreeView.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TicketingDetail/Views/PolicyView.swift
  Boolti/Boolti/Sources/UILayer/Ticket/TicketList/TicketListViewController.swift
Labels: v1.5.0
