Repository Nexters/Boolti-iOS, pull requests merged in 2024-10, with the labels that each got.

#358 Fix/#357 banner 노출 시점 변경
  Boolti/Boolti/Sources/UILayer/Concert/ConcertList/ConcertListViewController.swift
  Boolti/Boolti/Sources/UILayer/Concert/ConcertList/ConcertViewModel.swift
Labels: v1.6.4

#363 Feature/#360 출연진 리스트 구현 및 공연 정보 딥링크 제거
  Boolti/Boolti.xcodeproj/project.pbxproj
  Boolti/Boolti/Sources/Entities/Concert/ConcertCastTeamListEntity.swift
  Boolti/Boolti/Sources/Network/APIs/ConcertAPI.swift
  Boolti/Boolti/Sources/Network/DTO/Auth/Response/UserResponseDTO.swift
  Boolti/Boolti/Sources/Network/DTO/Concert/Request/ConcertCastTeamListRequestDTO.swift
  Boolti/Boolti/Sources/Network/DTO/Concert/Request/ConcertUserProfileRequestDTO.swift
  Boolti/Boolti/Sources/Network/DTO/Concert/Response/ConcertCastTeamListResponseDTO.swift
  Boolti/Boolti/Sources/Network/DTO/Concert/Response/ConcertUserProfileResponseDTO.swift
  Boolti/Boolti/Sources/Network/Foundation/NetworkProvider.swift
  Boolti/Boolti/Sources/Network/Repositories/Auth/AuthRepository.swift
  Boolti/Boolti/Sources/Network/Repositories/ConcertRepository.swift
  Boolti/Boolti/Sources/Network/Repositories/GiftingRepository.swift
  Boolti/Boolti/Sources/Network/Repositories/PushNotificationRepository.swift
  Boolti/Boolti/Sources/Network/Repositories/QRRepository.swift
  Boolti/Boolti/Sources/Network/Repositories/RepositoryType.swift
  Boolti/Boolti/Sources/Network/Repositories/ReservationsRepository.swift
  Boolti/Boolti/Sources/Network/Repositories/TicketingRepository.swift
  Boolti/Boolti/Sources/UILayer/Concert/ConcertDetail/ConcertDetailDIContainer.swift
  Boolti/Boolti/Sources/UILayer/Concert/ConcertDetail/ConcertDetailViewController.swift
  Boolti/Boolti/Sources/UILayer/Concert/ConcertDetail/ConcertDetailViewModel.swift
  Boolti/Boolti/Sources/UILayer/Concert/ConcertDetail/Views/CastTeamListCollectionViewCell.swift
  Boolti/Boolti/Sources/UILayer/Concert/ConcertDetail/Views/CastTeamListFooterView.swift
  Boolti/Boolti/Sources/UILayer/Concert/ConcertDetail/Views/CastTeamListHeaderView.swift
  Boolti/Boolti/Sources/UILayer/Concert/ConcertDetail/Views/EmptyCastTeamListView.swift
  Boolti/Boolti/Sources/UILayer/Concert/ConcertDetail/Views/SegmentedControlContainerView.swift
  Boolti/Boolti/Sources/UILayer/Concert/ConcertDetail/Views/UnderlineSegmentedControl.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Main/MyPageDIContainer.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/Main/ProfileDIContainer.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/Main/ProfileViewController.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/Main/ProfileViewModel.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/Main/Views/ProfileMainView.swift
Labels: v1.6.4

#365 Chore/#364 출연진 리스트 API 호출 타이밍 및 UI 수정
  Boolti/Boolti/Sources/UILayer/Concert/ConcertDetail/ConcertDetailViewController.swift
Labels: 1.7.1

#368 Release Version 1.7.0
  Boolti/Boolti.xcodeproj/project.pbxproj
  Boolti/Boolti/Sources/Entities/Concert/ConcertCastTeamListEntity.swift
  Boolti/Boolti/Sources/Network/APIs/ConcertAPI.swift
  Boolti/Boolti/Sources/Network/DTO/Auth/Response/UserResponseDTO.swift
  Boolti/Boolti/Sources/Network/DTO/Concert/Request/ConcertCastTeamListRequestDTO.swift
  Boolti/Boolti/Sources/Network/DTO/Concert/Request/ConcertUserProfileRequestDTO.swift
  Boolti/Boolti/Sources/Network/DTO/Concert/Response/ConcertCastTeamListResponseDTO.swift
  Boolti/Boolti/Sources/Network/DTO/Concert/Response/ConcertUserProfileResponseDTO.swift
  Boolti/Boolti/Sources/Network/Foundation/NetworkProvider.swift
  Boolti/Boolti/Sources/Network/Repositories/Auth/AuthRepository.swift
  Boolti/Boolti/Sources/Network/Repositories/ConcertRepository.swift
  Boolti/Boolti/Sources/Network/Repositories/GiftingRepository.swift
  Boolti/Boolti/Sources/Network/Repositories/PushNotificationRepository.swift
  Boolti/Boolti/Sources/Network/Repositories/QRRepository.swift
  Boolti/Boolti/Sources/Network/Repositories/RepositoryType.swift
  Boolti/Boolti/Sources/Network/Repositories/ReservationsRepository.swift
  Boolti/Boolti/Sources/Network/Repositories/TicketingRepository.swift
  Boolti/Boolti/Sources/UILayer/Concert/ConcertDetail/ConcertDetailDIContainer.swift
  Boolti/Boolti/Sources/UILayer/Concert/ConcertDetail/ConcertDetailViewController.swift
  Boolti/Boolti/Sources/UILayer/Concert/ConcertDetail/ConcertDetailViewModel.swift
  Boolti/Boolti/Sources/UILayer/Concert/ConcertDetail/Views/CastTeamListCollectionViewCell.swift
  Boolti/Boolti/Sources/UILayer/Concert/ConcertDetail/Views/CastTeamListFooterView.swift
  Boolti/Boolti/Sources/UILayer/Concert/ConcertDetail/Views/CastTeamListHeaderView.swift
  Boolti/Boolti/Sources/UILayer/Concert/ConcertDetail/Views/EmptyCastTeamListView.swift
  Boolti/Boolti/Sources/UILayer/Concert/ConcertDetail/Views/SegmentedControlContainerView.swift
  Boolti/Boolti/Sources/UILayer/Concert/ConcertDetail/Views/UnderlineSegmentedControl.swift
  Boolti/Boolti/Sources/UILayer/Concert/ConcertList/ConcertListViewController.swift
  Boolti/Boolti/Sources/UILayer/Concert/ConcertList/ConcertViewModel.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/Detail/GiftingDetail/Cells/CardImageCollectionViewCell.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/Detail/GiftingDetail/GiftingDetailViewController.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/Detail/GiftingDetail/Views/SelectCardView.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Main/MyPageDIContainer.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/EditProfile/EditProfileViewController.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/EditProfile/Views/EditIntroductionView.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/Main/ProfileDIContainer.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/Main/ProfileViewController.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/Main/ProfileViewModel.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/Main/Views/ProfileMainView.swift
Labels: ETC

#367 Fix/#366 선물하기 이미지 column 수정
  Boolti/Boolti.xcodeproj/project.pbxproj
  Boolti/Boolti/Sources/Entities/Ticketing/GiftCardImageEntity.swift
  Boolti/Boolti/Sources/Network/DTO/Gifting/Response/GiftCardImagesResponseDTO.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/Detail/GiftingDetail/GiftingDetailViewController.swift
Labels: 1.7.1
