Repository Nexters/Boolti-iOS, pull requests merged in 2024-11, with the labels that each got.

#374 Feature/#373 유저 식별코드 복사 버튼 생성
  Boolti/Boolti/Sources/UILayer/MyPage/Setting/SettingViewController.swift
Labels: 1.7.3

#376 Chore/#375 공연 정보 공유 포맷 변경
  Boolti/Boolti/Sources/Entities/Concert/ConcertDetailEntity.swift
  Boolti/Boolti/Sources/Global/Extensions/Date+.swift
  Boolti/Boolti/Sources/UILayer/Concert/ConcertDetail/ConcertDetailViewController.swift
Labels: 1.7.3

#370 Feature/#369 탈퇴한 회원 프로필 조회
  Boolti/Boolti/Sources/UILayer/Common/BooltiPopupView.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/Main/ProfileViewController.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/Main/ProfileViewModel.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/Main/Views/ProfileMainView.swift
Labels: v1.7.2

#378 Feature/#377 toss payments order name
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TossPayments/TossPaymentViewController.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TossPayments/TossPaymentsViewModel.swift
Labels: v1.7.2

#381 Feature/#379 프로필 링크 UI 수정 및 전체보기 뷰 구현
  Boolti/Boolti.xcodeproj/project.pbxproj
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/EditLink/EditLinkViewController.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/EditProfile/EditProfileViewController.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/EditProfile/Views/AddLinkHeaderView.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/LinkList/LinkListDIContainer.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/LinkList/LinkListViewController.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/LinkList/LinkListViewModel.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/Main/ProfileDIContainer.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/Main/ProfileViewController.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/Main/Views/ProfileLinkHeaderView.swift
Labels: v1.7.2

#382 Fix/#380 business info cell 재사용 이슈 해결
  Boolti/Boolti/Sources/UILayer/Concert/ConcertList/Cells/BusinessInfoCollectionViewCell.swift
  Boolti/Boolti/Sources/UILayer/Concert/ConcertList/ConcertListViewController.swift
Labels: v1.7.2

#389 Feature/#383 프로필 출연한 공연 UI 및 API 연결
  Boolti/Boolti.xcodeproj/project.pbxproj
  Boolti/Boolti/Sources/Entities/Auth/ProfileEntity.swift
  Boolti/Boolti/Sources/Network/DTO/Auth/Response/UserResponseDTO.swift
  Boolti/Boolti/Sources/Network/DTO/Concert/Response/ConcertUserProfileResponseDTO.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/Main/Cells/ProfileConcertCollectionViewCell.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/Main/ProfileDIContainer.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/Main/ProfileViewController.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/Main/ProfileViewModel.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/Main/Views/ProfileDataHeaderView.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/PerformedConcertList/Cells/PerformedConcertCollectionViewCell.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/PerformedConcertList/PerformedConcertListDIContainer.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/PerformedConcertList/PerformedConcertListViewController.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/PerformedConcertList/PerformedConcertListViewModel.swift
Labels: v1.7.2

#393 Feature/#385 프로필 편집 뷰 sns view 추가
  Boolti/Boolti.xcodeproj/project.pbxproj
  Boolti/Boolti/Sources/Global/Enums/SNSType.swift
  Boolti/Boolti/Sources/Network/DTO/Auth/Request/EditProfileRequestDTO.swift
  Boolti/Boolti/Sources/Network/DTO/Concert/Response/ConcertUserProfileResponseDTO.swift
  Boolti/Boolti/Sources/Network/Repositories/Auth/AuthRepository.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/EditProfile/Cells/EditLinkCollectionViewCell.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/EditProfile/Cells/EditSnsCollectionViewCell.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/EditProfile/EditProfileViewController.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/EditProfile/EditProfileViewModel.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/EditProfile/Views/AddLinkHeaderView.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/EditProfile/Views/EditSnsView.swift
Labels: v1.7.2

#390 Feature/#388 공연 상세 고도화 작업
  Boolti/Boolti.xcodeproj/project.pbxproj
  Boolti/Boolti/Resources/Assets.xcassets/grey_ticket_icon.imageset/Contents.json
  Boolti/Boolti/Resources/Assets.xcassets/grey_ticket_icon.imageset/ticket (3) 1.png
  Boolti/Boolti/Resources/Assets.xcassets/grey_ticket_icon.imageset/ticket (3) 1@2x.png
  Boolti/Boolti/Resources/Assets.xcassets/grey_ticket_icon.imageset/ticket (3) 1@3x.png
  Boolti/Boolti/Sources/Entities/Concert/ConcertDetailEntity.swift
  Boolti/Boolti/Sources/Network/DTO/Concert/Response/ConcertDetailResponseDTO.swift
  Boolti/Boolti/Sources/UILayer/Concert/ConcertDetail/ConcertDetailViewController.swift
  Boolti/Boolti/Sources/UILayer/Concert/ConcertDetail/ConcertDetailViewModel.swift
  Boolti/Boolti/Sources/UILayer/Concert/ConcertDetail/Views/ConcertPosterView.swift
  Boolti/Boolti/Sources/UILayer/Concert/ConcertDetail/Views/DatetimeInfoView.swift
  Boolti/Boolti/Sources/UILayer/Concert/ConcertDetail/Views/TicketSalesTimeView.swift
  Boolti/Boolti/Sources/UILayer/Concert/ConcertDetail/Views/TicketingPeriodView.swift
  Boolti/Boolti/Sources/UILayer/Concert/ConcertList/ConcertListViewController.swift
Labels: v1.7.2

#394 Feature/#386 프로필 sns 링크 추가 및 편집
  Boolti/Boolti.xcodeproj/project.pbxproj
  Boolti/Boolti/Sources/Global/Enums/SNSType.swift
  Boolti/Boolti/Sources/UILayer/Common/BooltiInputStackView.swift
  Boolti/Boolti/Sources/UILayer/Common/BooltiPopupView.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/EditProfile/EditProfileViewController.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/EditSns/Cells/SnsTypeCollectionViewCell.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/EditSns/EditSnsViewController.swift
Labels: v1.7.2

#396 Fix/#395 sns dto 변경 및 concertEntity 재사용
  Boolti/Boolti/Sources/Entities/Auth/ProfileEntity.swift
  Boolti/Boolti/Sources/Global/Enums/SNSType.swift
  Boolti/Boolti/Sources/Network/DTO/Auth/Request/EditProfileRequestDTO.swift
  Boolti/Boolti/Sources/Network/DTO/Auth/Response/UserResponseDTO.swift
  Boolti/Boolti/Sources/Network/DTO/Concert/Response/ConcertUserProfileResponseDTO.swift
  Boolti/Boolti/Sources/Network/Repositories/Auth/AuthRepository.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/Main/ProfileDIContainer.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/Main/ProfileViewController.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/Main/ProfileViewModel.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/PerformedConcertList/PerformedConcertListDIContainer.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/PerformedConcertList/PerformedConcertListViewController.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/PerformedConcertList/PerformedConcertListViewModel.swift
Labels: v1.7.2

#397 Chore/#392 선물하기 depositor field 삭제
  Boolti/Boolti/Sources/Network/DTO/Gifting/Request/FreeGiftingRequestDTO.swift
  Boolti/Boolti/Sources/Network/DTO/Gifting/Request/OrderGiftPaymentRequestDTO.swift
  Boolti/Boolti/Sources/Network/Repositories/GiftingRepository.swift
Labels: v1.7.2

#400 Feature/#399 프로필 편집 링크 순서 변경 구현
  Boolti/Boolti.xcodeproj/project.pbxproj
  Boolti/Boolti/Resources/Assets.xcassets/move.imageset/Contents.json
  Boolti/Boolti/Resources/Assets.xcassets/move.imageset/move.pdf
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/EditLink/EditLinkViewModel.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/EditProfile/Cells/EditLinkCollectionViewCell.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/EditProfile/Cells/EditSnsCollectionViewCell.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/EditProfile/EditProfileViewController.swift
Labels: v1.7.2

#398 Feature/#387 선물 취소 기능 추가 및 그외 QA 사항 반영
  Boolti/Boolti/Sources/Entities/Concert/ConcertDetailEntity.swift
  Boolti/Boolti/Sources/Entities/Ticket/TicketDetailItemEntity.swift
  Boolti/Boolti/Sources/Network/APIs/TicketAPI.swift
  Boolti/Boolti/Sources/Network/DTO/Ticket/Response/TicketDetailResponseDTO.swift
  Boolti/Boolti/Sources/UILayer/Common/BooltiPopupView.swift
  Boolti/Boolti/Sources/UILayer/Concert/ConcertDetail/ConcertDetailViewController.swift
  Boolti/Boolti/Sources/UILayer/MyPage/ReservationDetail/GiftReservationDetail/GiftReservationDetailViewController.swift
  Boolti/Boolti/Sources/UILayer/MyPage/ReservationDetail/TicketReservationDetail/TicketReservationDetailViewController.swift
  Boolti/Boolti/Sources/UILayer/Ticket/TicketDetail/TicketDetailViewController.swift
  Boolti/Boolti/Sources/UILayer/Ticket/TicketDetail/TicketDetailViewModel.swift
  Boolti/Boolti/Sources/UILayer/Ticket/TicketList/TicketListViewController.swift
Labels: v1.7.2

#402 Chore/#401 선물 등록 팝업 문구 수정 (남이 선물한 경우)
  Boolti/Boolti.xcodeproj/project.pbxproj
  Boolti/Boolti/Sources/UILayer/Common/BooltiPopupView.swift
Labels: v1.7.2

#404 Chore/#403 프로필 메인 디자인 QA 반영
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/Main/Cells/ProfileSnsCollectionViewCell.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/Main/ProfileViewController.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/Main/Views/ProfileDataHeaderView.swift
Labels: v1.7.2

#406 Chore/#405 sns 편집 디자인 qa 반영
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/EditSns/EditSnsViewController.swift
Labels: v1.8.0

#408 Chore/#407 프로필 sns 앱으로 연결
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/Main/ProfileViewController.swift
Labels: v1.8.0

#410 Chore/#409 공연 상세 페이지를 통한 내 프로필 접근 수정 가능하도록 변경
  Boolti/Boolti/Sources/UILayer/Concert/ConcertDetail/ConcertDetailDIContainer.swift
  Boolti/Boolti/Sources/UILayer/Concert/ConcertDetail/ConcertDetailViewController.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/Main/ProfileDIContainer.swift
Labels: v1.8.0

#414 Feature/#411 sns, 링크 삭제 토스트 추가
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/EditLink/EditLinkViewController.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/EditSns/EditSnsViewController.swift
Labels: v1.8.0

#415 Chore/#412 sns, 링크 추가 시 index 0 insert 대신 append로 수정
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/EditProfile/EditProfileViewController.swift
Labels: v1.8.0

#416 Chore/#413 share concert text format
  Boolti/Boolti/Sources/Entities/Concert/ConcertDetailEntity.swift
  Boolti/Boolti/Sources/Global/Extensions/Date+.swift
Labels: v1.8.0

#418 Fix/#417 9 design qa
  Boolti/Boolti/Sources/UILayer/Concert/ConcertDetail/ConcertDetailViewController.swift
  Boolti/Boolti/Sources/UILayer/Concert/ConcertDetail/Views/ContentInfoView.swift
  Boolti/Boolti/Sources/UILayer/Concert/ConcertDetail/Views/DatetimeInfoView.swift
  Boolti/Boolti/Sources/UILayer/Concert/ConcertDetail/Views/OrganizerInfoView.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/EditLink/EditLinkViewController.swift
Labels: v1.8.0

#420 Fix/#419 design qa2
  Boolti/Boolti/Sources/UILayer/Common/BooltiNavigationBar.swift
  Boolti/Boolti/Sources/UILayer/Concert/ConcertDetail/ConcertDetailViewController.swift
  Boolti/Boolti/Sources/UILayer/Concert/ConcertDetail/Views/ContentInfoView.swift
  Boolti/Boolti/Sources/UILayer/Concert/ConcertDetail/Views/DatetimeInfoView.swift
  Boolti/Boolti/Sources/UILayer/Concert/ConcertDetail/Views/OrganizerInfoView.swift
  Boolti/Boolti/Sources/UILayer/Concert/ConcertDetail/Views/PlaceInfoView.swift
  Boolti/Boolti/Sources/UILayer/Concert/ConcertDetail/Views/TicketSalesTimeView.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/EditLink/EditLinkViewController.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/Main/ProfileViewController.swift
Labels: v1.8.0

#422 Fix/#421 사파리 브라우저를 통해서 웹 페이지 열기 구현
  Boolti/Boolti/Sources/UILayer/BusinessInfo/BusinessInfoViewController.swift
  Boolti/Boolti/Sources/UILayer/Common/BooltiViewController.swift
  Boolti/Boolti/Sources/UILayer/Concert/ConcertList/ConcertListViewController.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Main/MypageViewController.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/LinkList/LinkListViewController.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/Main/ProfileViewController.swift
Labels: v1.8.0

#424 Fix/#423 design qa 3
  Boolti/Boolti.xcodeproj/project.pbxproj
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/Main/ProfileViewController.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/Main/ProfileViewModel.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/Main/Views/ProfileDataHeaderView.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Profile/PerformedConcertList/Cells/PerformedConcertCollectionViewCell.swift
Labels: v1.8.0

#426 Fix/#425 예매 완료 케이스 처리
  Boolti/Boolti/Sources/Global/Extensions/Date+.swift
  Boolti/Boolti/Sources/Network/DTO/Concert/Response/ConcertDetailResponseDTO.swift
Labels: v1.8.0
