Repository Nexters/Boolti-iOS, pull requests merged in 2024-08, with the labels that each got.

#321 Feature/#319 마이페이지 메인 UI 변경
  Boolti/Boolti.xcodeproj/project.pbxproj
  Boolti/Boolti/Resources/Assets.xcassets/add_concert.imageset/Contents.json
  Boolti/Boolti/Resources/Assets.xcassets/add_concert.imageset/add_concert.pdf
  Boolti/Boolti/Resources/Assets.xcassets/mypage_logo.imageset/Contents.json
  Boolti/Boolti/Resources/Assets.xcassets/mypage_logo.imageset/mypage_logo.pdf
  Boolti/Boolti/Resources/Assets.xcassets/profile.imageset/Contents.json
  Boolti/Boolti/Resources/Assets.xcassets/profile.imageset/profile.pdf
  Boolti/Boolti/Resources/Assets.xcassets/receipt.imageset/Contents.json
  Boolti/Boolti/Resources/Assets.xcassets/receipt.imageset/receipt.pdf
  Boolti/Boolti/Sources/UILayer/MyPage/Main/MyPageDIContainer.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Main/MyPageDestination.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Main/MyPageViewModel.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Main/MypageViewController.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Main/Views/MypageContentView.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Main/Views/MypageProfileView.swift
Labels: v1.6.1

#323 Feature/#322 마이페이지 설정 로그아웃, 삭제 추가
  Boolti/Boolti/Sources/UILayer/MyPage/Logout/LogoutViewController.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Setting/SettingDIContainer.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Setting/SettingViewController.swift
Labels: v1.6.1

#331 Fix/#330 로그인 버튼 옆 마진 수정
  Boolti/Boolti/Sources/UILayer/MyPage/Main/Views/MypageProfileView.swift
Labels: v1.6.1

#332 Release Version 1.6.1
  Boolti/Boolti.xcodeproj/project.pbxproj
  Boolti/Boolti/Resources/Assets.xcassets/add_concert.imageset/Contents.json
  Boolti/Boolti/Resources/Assets.xcassets/add_concert.imageset/add_concert.pdf
  Boolti/Boolti/Resources/Assets.xcassets/mypage_logo.imageset/Contents.json
  Boolti/Boolti/Resources/Assets.xcassets/mypage_logo.imageset/mypage_logo.pdf
  Boolti/Boolti/Resources/Assets.xcassets/profile.imageset/Contents.json
  Boolti/Boolti/Resources/Assets.xcassets/profile.imageset/profile.pdf
  Boolti/Boolti/Resources/Assets.xcassets/receipt.imageset/Contents.json
  Boolti/Boolti/Resources/Assets.xcassets/receipt.imageset/receipt.pdf
  Boolti/Boolti/Sources/UILayer/MyPage/Logout/LogoutViewController.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Main/MyPageDIContainer.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Main/MyPageDestination.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Main/MyPageViewModel.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Main/MypageViewController.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Main/Views/MypageContentView.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Main/Views/MypageProfileView.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Setting/SettingDIContainer.swift
  Boolti/Boolti/Sources/UILayer/MyPage/Setting/SettingViewController.swift
Labels: ETC

#334 Feature/#324 약관 웹 뷰 구현하기
  Boolti/Boolti.xcodeproj/project.pbxproj
  Boolti/Boolti/Sources/Global/Extensions/Preview.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/Detail/GiftingDetail/GiftingDetailViewController.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/Detail/TicketingDetail/TicketingDetailViewController.swift
  Boolti/Boolti/Sources/UILayer/Concert/Ticketing/Detail/ViewController/AgreementViewController.swift
Labels: 1.6.2

#335 Feature/#333 공연 리스트 사이 공연 유도 배너 구현
  Boolti/Boolti.xcodeproj/project.pbxproj
  Boolti/Boolti/Resources/Assets.xcassets/banner_background.imageset/Contents.json
  Boolti/Boolti/Resources/Assets.xcassets/banner_background.imageset/banner_background.png
  Boolti/Boolti/Resources/Assets.xcassets/banner_fire.imageset/Contents.json
  Boolti/Boolti/Resources/Assets.xcassets/banner_fire.imageset/banner_fire.png
  Boolti/Boolti/Sources/UILayer/Concert/ConcertList/Cells/BannerCollectionViewCell.swift
  Boolti/Boolti/Sources/UILayer/Concert/ConcertList/ConcertListViewController.swift
  Boolti/Boolti/Sources/UILayer/Concert/ConcertList/ConcertViewModel.swift
Labels: 1.6.2
